import turtle
turtle.color("red")
tela = turtle.Screen()
turtle.begin_fill()
turtle.pensize(3)
turtle.left(50)
turtle.forward(133)
turtle.circle(50,200)
turtle.right(140)
turtle.circle(50,200)
turtle.forward(133)
turtle.end_fill()
tela.exitonclick()